# Generated by Django 5.0.2 on 2024-02-28 07:06

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restuarants',
            options={'get_latest_by': 'date_opened', 'ordering': [django.db.models.functions.text.Lower('date_opened')]},
        ),
        migrations.AddField(
            model_name='sales',
            name='expendature',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
