# Generated by Django 5.0.2 on 2024-03-04 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_restuarants_options_sales_expendature'),
    ]

    operations = [
        migrations.AddField(
            model_name='restuarants',
            name='capacity',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
