# Generated by Django 5.0.2 on 2024-03-12 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_product_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restuarants',
            options={},
        ),
    ]
