# Generated by Django 5.0.2 on 2024-03-13 10:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.CheckConstraint(check=models.Q(('rating__lse', 5), ('ratings__gte', 1)), name='rating_value_valid', violation_error_message='Rating invalid, must be fall between 1 to 5'),
        ),
    ]
