# Generated by Django 5.0.2 on 2024-03-13 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rating_rating_value_valid'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rating',
            name='rating_value_valid',
        ),
    ]
